import { invoke, isTauri } from '@tauri-apps/api/core';
import { listen } from '@tauri-apps/api/event';
import { getCurrentWindow } from '@tauri-apps/api/window';
import type { MainRequest } from './generated/MainRequest';
import type { PetRequest } from './generated/PetRequest';
import type { Reply } from './generated/Reply';
import type { PetReply } from './generated/PetReply';
export const native = isTauri();

declare global {
  interface Window { __DROPLET_TEST_INVOKE__?: (surface: string, request: unknown) => Promise<{ ok: boolean; value?: unknown; error?: unknown }> }
}
async function sendOnce<T>(surface: 'main' | 'pet', request: MainRequest | PetRequest): Promise<T> {
  if (native) return invoke<T>(`${surface}_command`, { request });
  // Compiled out of production. Browser tests exercise the real, isolated Rust core.
  if (import.meta.env.DEV && window.__DROPLET_TEST_INVOKE__) {
    const result = await window.__DROPLET_TEST_INVOKE__(surface, request);
    if (!result.ok) throw result.error;
    return result.value as T;
  }
  // Static, read-only DTOs generated by Rust; no second business implementation.
  if (request.type === 'view') {
    const response = await fetch(surface === 'main' ? '/preview.json' : '/pet-preview.json');
    if (!response.ok) throw new Error('Preview data is unavailable.');
    return { type: 'view', value: await response.json() } as T;
  }
  throw new Error('Open the desktop app to use this action. This browser preview is read-only.');
}
async function send<T>(surface: 'main' | 'pet', request: MainRequest | PetRequest): Promise<T> {
  // Tauri may load the renderer before native setup has registered the core.
  // Retry only this startup read; writes and other errors retain their normal behavior.
  for (let attempt = 0; ; attempt++) {
    try { return await sendOnce<T>(surface, request); }
    catch (error) {
      if (request.type !== 'view' || errorText(error) !== 'Droplet is still starting.' || attempt >= 8) throw error;
      await new Promise(resolve => setTimeout(resolve, 150 * (attempt + 1)));
    }
  }
}
export const mainCommand = (request: MainRequest) => send<Reply>('main', request);
export const petCommand = (request: PetRequest) => send<PetReply>('pet', request);
export function errorText(error: unknown): string {
  if (error && typeof error === 'object' && 'message' in error) return String(error.message);
  return String(error);
}
export async function onChanged(callback: () => void): Promise<() => void> {
  return native ? listen('state-changed', callback) : () => {};
}
export async function onError(callback: (error: unknown) => void): Promise<() => void> {
  return native ? listen('app-error', event => callback(event.payload)) : () => {};
}
export async function dragLauncher(): Promise<void> { if (native) await getCurrentWindow().startDragging(); }
